package com.example.pixvi.network.response.Home.HomePage

data class AppModel(
    val caption: String,
    val create_date: String,
    val height: Int?,
    val id: Int,
    val illust_ai_type: Int?,
    val illust_book_style: Int?,
    val image_urls: ImageUrls,
    val is_bookmarked: Boolean,
    val is_muted: Boolean,
    val is_mypixiv_only: Boolean?,
    val is_original: Boolean?,
    val is_x_restricted: Boolean?,
    val meta_pages: List<MetaPage>?,
    val meta_single_page: MetaSinglePage?,
    val novel_ai_type: Int?,
    val page_count: Int,
    val restrict: Int,
    val sanity_level: Int?,
    val series: Series?,
    val tags: List<Tag>,
    val text_length: Int?,
    val title: String,
    val tools: List<String>?,
    val total_bookmarks: Int,
    val total_comments: Int?,
    val total_view: Int,
    val type: String?,
    val user: User,
    val visible: Boolean,
    val width: Int?,
    val x_restrict: Int
)